name: CI - Build and Test .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Klona koden
        uses: actions/checkout@v4

      - name: Installera .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Återställ beroenden
        run: dotnet restore

      - name: Bygg projektet
        run: dotnet build --no-restore --configuration Release

      - name: Kör tester
        run: dotnet test --no-build --verbosity normal
